# ARRAY
If a list containes only numbers, array.array is a more efficient replacement.
Arrays support all mutable sequence.

In [ ]:
from array import array
a=array(‘d’, (random() for I in range(10**7)))
#Array a contains 10 million double float values (are double float because we give the parameter ‘d’).

# NUMPY

NumPy implements multi-dimensional, homogeneous arrays and matrix types that hold not only numbers but also user-defined records, and provides efficient element-wise operations.

In [1]:
import numpy as np
from time import perf_counter as pc # timer to know the elapsed for 3 divisions
a=np.arange(12)
print(a)
print(a.shape) #inspect the array, (12, ) this is one dimensional array with 12 elements
a.shape=3, 4 #change the shape of the matrix in 3 lines with 4 columsn, 3 dimensions with 4 elements for each
print(a)
a.transpose() #Create a new array by transposing (swapping columns with rows).
# print(a)
# print(a[0])
# print(a[:, 1])
b=np.array([1508181.34597761, 267640.55257131, 2283280.22186973])
b.shape=3, 1
print(b)
t0=pc()
b/=3
print(pc()-t0)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1508181.34597761]
 [ 267640.55257131]
 [2283280.22186973]]
0.0010245809971820563


# DEQUES AND QUEUES
The .append and .pop methods make a list usable as a stack or a queue (if you
use .append and .pop(0), you get FIFO behavior). But inserting and removing from
the head of a list (the 0-index end) is costly because the entire list must be shifted in
memory.
The class collections.deque is a thread-safe double-ended queue designed for fast
inserting and removing from both ends.
If you have to remove the value in the middle the operation could be long and not so efficient.
It’s efficient for FIFO applications (First In First Out).

# DICTIONARIES
Example of using dictionaries from a list of tuples

In [ ]:
dial_codes = [
(880, 'Bangladesh'),
(55, 'Brazil'),
(86, 'China'),
(91, 'India'),
(62, 'Indonesia'),
(81, 'Japan'),
(234, 'Nigeria'),
(92, 'Pakistan'),
(7,'Russia'),
(1,'United States'),
]
country_dial={country: code for code, country in dial_codes}
print(country_dial)
print({code:country.upper() for country, code in sorted(country_dial.items()) if code<50})
#country_dial.items() restituisce la prima coppia country, code del dizionario, altrimenti da errore
#perche rileva troppi items e lui invece se ne aspetta due country e code

## UNPACKING MAPPINGS with **kwargs

First, we can apply ** to more than one argument in a function call. This works when
keys are all strings and unique across all arguments (because duplicate keyword argu‐
ments are forbidden):


In [2]:
def dump(**kwargs):
    return kwargs
def main():
    b=dump(**{'x':1}, y=2, **{'z': 3})
    print(b)
    # a={'a':0, **{'x':1}, 'y':2, **{'z':2, 'x':4}}
    # print(a)

main()

{'x': 1, 'y': 2, 'z': 3}


MERGING MAPPINGS WITH |


In [7]:
d1 = {'a': 1, 'b': 3}
d2 = {'a': 2, 'b': 4, 'c': 6}
print(d1 | d2)

{'a': 2, 'b': 4, 'c': 6}


## Pattern matching with Mapping

The match/case statement supports subjects that are mapping objects. Patterns for
mappings look like dict literals, but they can match instances of any actual or virtual
subclass of collections.abc.Mapping


In [8]:
def get_creators(record: dict) -> list: #this function wait a record of dict type and return a list
    match record:
        case {'type': 'book', 'api': 2, 'authors': [*names]}:
         return names
        case {'type': 'book', 'api': 1, 'author': name}:
          return [name]
        case {'type': 'book'}:
         raise ValueError(f"Invalid 'book' record: {record!r}")
        case {'type': 'movie', 'director': name}:
         return [name]
        case _:
          raise ValueError(f'Invalid record: {record!r}')
def main():
    b1={'api':1, 'author':'Douglas Hofstadter', 'type':'book', 'title':'Gödel, Escher, Bach'}
    print(get_creators(b1))
main()

['Douglas Hofstadter']


## collections.Counter
A mapping that holds an integer count for each key. Updating an existing key adds to
its count. This can be used to count instances of hashable objects or as a multiset (dis‐
cussed later in this section). Counter implements the + and - operators to combine
tallies, and other useful methods such as most_common([n]), which returns an
ordered list of tuples with the n most common items and their counts

In [10]:
import collections
ct=collections.Counter('ciao')
print(ct)

Counter({'c': 1, 'i': 1, 'a': 1, 'o': 1})
